// <auto-generated />
    using System.Xml.Serialization;

namespace QBCH.Lib.qcb_xml.v3_0
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ТипУсловиеЗапрета {
        
        private string датаЗаявленияField;
        
        private string времяЗаявленияField;
        
        private string началоДействияField;
        
        private СправочникУсловияЗапрета valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttribute()]
        public string ДатаЗаявления {
            get {
                return this.датаЗаявленияField;
            }
            set {
                this.датаЗаявленияField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttribute()]
        public string ВремяЗаявления {
            get {
                return this.времяЗаявленияField;
            }
            set {
                this.времяЗаявленияField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttribute()]
        public string НачалоДействия {
            get {
                return this.началоДействияField;
            }
            set {
                this.началоДействияField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public СправочникУсловияЗапрета Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
}
